environment:
  image: Visual Studio 2017
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: '13'

platform:
  - x64
  - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - if %PLATFORM% == "x64" call "C:\Program Files (x86)\Microsoft Visual Studio %MSVS_TOOLSET%.0\VC\vcvarsall.bat" amd64
  - if %PLATFORM% == "x86" call "C:\Program Files (x86)\Microsoft Visual Studio %MSVS_TOOLSET%.0\VC\vcvarsall.bat" x86
  - if "%PLATFORM%" == "x64" set FB_ZIP=Firebird-3.0.4.33054-0_x64.zip
  - if "%PLATFORM%" == "x86" set FB_ZIP=Firebird-3.0.4.33054-0_Win32.zip
  - ps: Start-FileDownload "https://github.com/FirebirdSQL/firebird/releases/download/R3_0_4/$env:FB_ZIP"
  - 7z x -oC:\Firebird %FB_ZIP%
  - set PATH=C:\Firebird;%PATH%
  - yarn
  - yarn bootstrap
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"

artifacts:
  - path: packages\node-firebird-native-api\build\Release
    name: node-firebird-native-api
    type: zip

build: off
test: off
deploy: off
