name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2019
          - windows-2022
          - windows-2025
          - macos-15
        node-version:
          - 20.x
          - 22.x
          - 24.x
          - 25.x

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Node.js corepack
        run: |
          corepack enable

      - name: Firebird install (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get install libtommath1 libtomcrypt1
          wget -nv -O Firebird-4.0.6.3221-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/v4.0.6/Firebird-4.0.6.3221-0.amd64.tar.gz"
          tar xzvf Firebird-4.0.6.3221-0.amd64.tar.gz
          (cd Firebird-4.0.6.3221-0.amd64; sudo ./install.sh -silent)
          sudo usermod -a -G firebird `whoami`
          sudo gpasswd -r firebird

      - name: Firebird install (MacOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          wget -nv -O Firebird-5.0.3.1683-0-macos-arm64.pkg "https://github.com/FirebirdSQL/firebird/releases/download/v5.0.3/Firebird-5.0.3.1683-0-macos-arm64.pkg"
          sudo installer -verbose -pkg "Firebird-5.0.3.1683-0-macos-arm64.pkg" -target /

      - name: Firebird install (Windows)
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        run: |
          set FB_ZIP=Firebird-4.0.6.3221-0-x64.zip
          powershell Invoke-WebRequest "https://github.com/FirebirdSQL/firebird/releases/download/v4.0.6/$env:FB_ZIP" -OutFile "$env:FB_ZIP"
          7z x -oC:\Firebird %FB_ZIP%

      - name: Build
        shell: bash
        run: |
          yarn
          yarn bootstrap

      - name: Test (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sg firebird -c "LD_LIBRARY_PATH=/usr/lib64 yarn test"

      - name: Test (MacOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          sudo mkdir `pwd`/tmp-node-fb
          sudo chmod 777 `pwd`/tmp-node-fb
          export ISC_USER=sysdba
          export ISC_PASSWORD=masterkey
          export NODE_FB_TEST_TMP_DIR=`pwd`/tmp-node-fb
          yarn test

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        run: |
          set PATH=C:\Firebird;%PATH%
          call yarn test

      - name: Upload native-api-${{ matrix.os }}-${{ matrix.node-version }}
        uses: actions/upload-artifact@v6
        with:
          name: native-api-${{ matrix.os }}-${{ matrix.node-version }}
          path: packages/node-firebird-native-api

      - name: Upload driver-${{ matrix.os }}-${{ matrix.node-version }}
        uses: actions/upload-artifact@v6
        with:
          name: driver-${{ matrix.os }}-${{ matrix.node-version }}
          path: packages/node-firebird-driver

      - name: Upload driver-native-${{ matrix.os }}-${{ matrix.node-version }}
        uses: actions/upload-artifact@v6
        with:
          name: driver-native-${{ matrix.os }}-${{ matrix.node-version }}
          path: packages/node-firebird-driver-native
